SELECT SUM(
        CASE
            WHEN C.CURRENCY_CODE = 'EUR' THEN P.AMOUNT
            ELSE P.AMOUNT * CR.EXCHANGE_RATE_TO_EUR
        END
    ) AS SUM_AMOUNT_EUR,
    P.TRANSACTION_DATE
FROM PAYMENTS P
    INNER JOIN CURRENCIES C ON P.CURRENCY = C.CURRENCY_ID
    LEFT JOIN CURRENCY_RATES CR ON P.CURRENCY = CR.CURRENCY_ID
    AND P.TRANSACTION_DATE = CR.EXCHANGE_DATE
    LEFT JOIN BLACKLIST B ON P.USER_ID_SENDER = B.USER_ID
WHERE C.END_DATE IS NULL
    AND B.USER_ID IS NULL
GROUP BY P.TRANSACTION_DATE;